import Head from "next/head";

function Navbar() {
  return (
    <div className="flex h-16 flex-row items-center justify-between border-b border-white bg-black px-24 text-white">
      <h2>logo</h2>
      <ul className="flex flex-row justify-between gap-6">
        <li>home</li>
        <li>about</li>
        <li>projects</li>
        <li>contact</li>
      </ul>
    </div>
  );
}

function Hero() {
  return (
    <>
      <img
        src="/heroimg.png"
        alt="heroimg.png"
        className="relative h-full w-full"
      />
      <h2 className="absolute bottom-0 w-[40%] pb-8 pl-4 text-[64px] text-white">
        A PORTFOLIO BUILT WITH <span className="text-[#31C58F]">REACT</span>JS
      </h2>
    </>
  );
}

function About() {
  return <div className="text-black">About</div>;
}

function AboutTwo() {
  return <div className="text-black">About Two</div>;
}

function Projects() {
  return <div className="text-white">Projects</div>;
}

function Contact() {
  return <div className="text-white">Contact</div>;
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="h-[calc(100vh-64px)] bg-gradient-to-b from-[#000] to-[#252525] px-24 py-8">
        <Hero />
      </div>

      <div className="min-h-screen bg-gradient-to-b from-[#252525] to-[#FFF] p-6">
        <About />
      </div>
      <div className="min-h-screen bg-gradient-to-b from-[#FFF] to-[#252525] p-6">
        <AboutTwo />
      </div>

      <div className="min-h-screen bg-[#252525] p-6">
        <Projects />
      </div>
      <div className="min-h-screen bg-gradient-to-b from-[#252525] to-[#000] p-6">
        <Contact />
      </div>
    </>
  );
}
