import Head from "next/head";

function Navbar() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#000] to-[#252525] p-6">
      <div className="flex flex-row justify-between border-b border-white px-4 pb-4 text-white">
        <h2>logo</h2>
        <ul className="flex flex-row justify-between gap-6">
          <li>home</li>
          <li>about</li>
          <li>projects</li>
          <li>contact</li>
        </ul>
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </>
  );
}
